#
# CircleCI 2.0
#
version: 2
jobs:
  build:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Terraform Apply
          command: |
            terraform init
            terraform apply -auto-approve

workflows:
  version: 2
  lambda:
    jobs:
      - build
